#!/usr/bin/env python3


#Each new term in the Fibonacci sequence is generated by adding the 
#previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not
#exceed four million, find the sum of the even-valued terms.


def fib(n):
    prev, cur = 0, 1
    while cur < n:
        if cur % 2 == 0:
            yield cur
        temp = prev
        prev = cur
        cur = temp + prev


if __name__ == '__main__':
    solution = sum(fib(4000000))
    print(solution)
